ERROR 2023-01-13 17:17:53,400 exception 135 Internal Server Error: /register/
Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 65, in __getitem__
    return self._engines[alias]
KeyError: 'jinja2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\module_loading.py", line 23, in import_string
    return getattr(module, class_name)
AttributeError: module 'my_jango.utils' has no attribute 'jinja2_environment'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\project\django\git_dj\my_jango\my_jango\apps\users\views.py", line 11, in get
    return render(request, 'register.html')
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 18, in get_template
    engines = _engine_list(using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 72, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 89, in all
    return [self[alias] for alias in self]
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 89, in <listcomp>
    return [self[alias] for alias in self]
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\backends\jinja2.py", line 29, in __init__
    environment_cls = import_string(environment)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\module_loading.py", line 27, in import_string
    six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\module_loading.py", line 23, in import_string
    return getattr(module, class_name)
ImportError: Module "my_jango.utils" does not define a "jinja2_environment" attribute/class
ERROR 2023-01-13 17:17:53,578 basehttp 124 "GET /register/ HTTP/1.1" 500 136569
WARNING 2023-01-13 17:17:53,785 base 152 Not Found: /favicon.ico
WARNING 2023-01-13 17:17:53,786 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2138
ERROR 2023-01-13 17:18:23,637 exception 135 Internal Server Error: /register
Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 65, in __getitem__
    return self._engines[alias]
KeyError: 'jinja2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\module_loading.py", line 23, in import_string
    return getattr(module, class_name)
AttributeError: module 'my_jango.utils' has no attribute 'jinja2_environment'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\project\django\git_dj\my_jango\my_jango\apps\users\views.py", line 11, in get
    return render(request, 'register.html')
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 18, in get_template
    engines = _engine_list(using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 72, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 89, in all
    return [self[alias] for alias in self]
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 89, in <listcomp>
    return [self[alias] for alias in self]
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\backends\jinja2.py", line 29, in __init__
    environment_cls = import_string(environment)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\module_loading.py", line 27, in import_string
    six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\module_loading.py", line 23, in import_string
    return getattr(module, class_name)
ImportError: Module "my_jango.utils" does not define a "jinja2_environment" attribute/class
ERROR 2023-01-13 17:18:23,687 basehttp 124 "GET /register HTTP/1.1" 500 136337
ERROR 2023-01-13 17:18:43,117 exception 135 Internal Server Error: /register/
Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 65, in __getitem__
    return self._engines[alias]
KeyError: 'jinja2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\module_loading.py", line 23, in import_string
    return getattr(module, class_name)
AttributeError: module 'my_jango.utils' has no attribute 'jinja2_environment'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\project\django\git_dj\my_jango\my_jango\apps\users\views.py", line 11, in get
    return render(request, 'register.html')
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 18, in get_template
    engines = _engine_list(using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 72, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 89, in all
    return [self[alias] for alias in self]
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 89, in <listcomp>
    return [self[alias] for alias in self]
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\backends\jinja2.py", line 29, in __init__
    environment_cls = import_string(environment)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\module_loading.py", line 27, in import_string
    six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\module_loading.py", line 23, in import_string
    return getattr(module, class_name)
ImportError: Module "my_jango.utils" does not define a "jinja2_environment" attribute/class
ERROR 2023-01-13 17:18:43,165 basehttp 124 "GET /register/ HTTP/1.1" 500 136352
ERROR 2023-01-13 17:19:30,424 exception 135 Internal Server Error: /register/
Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 65, in __getitem__
    return self._engines[alias]
KeyError: 'jinja2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\module_loading.py", line 23, in import_string
    return getattr(module, class_name)
AttributeError: module 'my_jango.utils' has no attribute 'jinja2_environment'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\project\django\git_dj\my_jango\my_jango\apps\users\views.py", line 11, in get
    return render(request, 'register.html')
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 18, in get_template
    engines = _engine_list(using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 72, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 89, in all
    return [self[alias] for alias in self]
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 89, in <listcomp>
    return [self[alias] for alias in self]
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\backends\jinja2.py", line 29, in __init__
    environment_cls = import_string(environment)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\module_loading.py", line 27, in import_string
    six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\module_loading.py", line 23, in import_string
    return getattr(module, class_name)
ImportError: Module "my_jango.utils" does not define a "jinja2_environment" attribute/class
ERROR 2023-01-13 17:19:30,481 basehttp 124 "GET /register/ HTTP/1.1" 500 136487
WARNING 2023-01-13 17:20:09,634 base 152 Not Found: /favicon.ico/
WARNING 2023-01-13 17:20:09,635 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 404 2141
INFO 2023-01-13 17:20:36,839 basehttp 124 "GET /static/images/adv01.jpg HTTP/1.1" 200 39831
ERROR 2023-01-13 17:20:45,856 exception 135 Internal Server Error: /register/
Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 65, in __getitem__
    return self._engines[alias]
KeyError: 'jinja2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\module_loading.py", line 23, in import_string
    return getattr(module, class_name)
AttributeError: module 'my_jango.utils' has no attribute 'jinja2_environment'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\project\django\git_dj\my_jango\my_jango\apps\users\views.py", line 11, in get
    return render(request, 'register.html')
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 18, in get_template
    engines = _engine_list(using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 72, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 89, in all
    return [self[alias] for alias in self]
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 89, in <listcomp>
    return [self[alias] for alias in self]
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\backends\jinja2.py", line 29, in __init__
    environment_cls = import_string(environment)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\module_loading.py", line 27, in import_string
    six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\utils\module_loading.py", line 23, in import_string
    return getattr(module, class_name)
ImportError: Module "my_jango.utils" does not define a "jinja2_environment" attribute/class
ERROR 2023-01-13 17:20:45,909 basehttp 124 "GET /register/ HTTP/1.1" 500 136352
INFO 2023-01-13 17:22:27,101 basehttp 124 "GET /register/ HTTP/1.1" 200 3696
INFO 2023-01-13 17:22:27,115 basehttp 124 "GET /static/css/reset.css HTTP/1.1" 200 638
INFO 2023-01-13 17:22:27,116 basehttp 124 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12941
INFO 2023-01-13 17:22:27,117 basehttp 124 "GET /static/css/main.css HTTP/1.1" 200 40091
INFO 2023-01-13 17:22:27,120 basehttp 124 "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289307
INFO 2023-01-13 17:22:27,126 basehttp 124 "GET /static/js/register.js HTTP/1.1" 200 2974
INFO 2023-01-13 17:22:27,134 basehttp 124 "GET /static/images/logo.png HTTP/1.1" 200 7450
INFO 2023-01-13 17:22:27,135 basehttp 124 "GET /static/images/pic_code.jpg HTTP/1.1" 200 4507
INFO 2023-01-13 17:22:27,162 basehttp 124 "GET /static/images/interval_line.png HTTP/1.1" 200 1123
INFO 2023-01-13 17:22:27,163 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 200 3935
INFO 2023-01-13 17:22:27,164 basehttp 124 "GET /static/images/register_banner.png HTTP/1.1" 200 54894
INFO 2023-01-13 17:48:10,852 basehttp 124 "GET /admin HTTP/1.1" 301 0
INFO 2023-01-13 17:48:10,983 basehttp 124 "GET /admin/ HTTP/1.1" 302 0
ERROR 2023-01-13 17:48:11,021 exception 135 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 215, in _get_response
    response = response.render()
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\response.py", line 107, in render
    self.content = self.rendered_content
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\response.py", line 82, in rendered_content
    template = self.resolve_template(self.template_name)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\response.py", line 64, in resolve_template
    return select_template(template, using=self.using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 53, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: admin/login.html
ERROR 2023-01-13 17:48:11,087 basehttp 124 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 85679
INFO 2023-01-13 17:48:20,225 basehttp 124 "GET /admin/ HTTP/1.1" 302 0
ERROR 2023-01-13 17:48:20,231 exception 135 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 215, in _get_response
    response = response.render()
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\response.py", line 107, in render
    self.content = self.rendered_content
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\response.py", line 82, in rendered_content
    template = self.resolve_template(self.template_name)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\response.py", line 64, in resolve_template
    return select_template(template, using=self.using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 53, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: admin/login.html
ERROR 2023-01-13 17:48:20,264 basehttp 124 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 85679
INFO 2023-01-13 17:48:42,954 basehttp 124 "GET /admin/ HTTP/1.1" 302 0
ERROR 2023-01-13 17:48:42,959 exception 135 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 215, in _get_response
    response = response.render()
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\response.py", line 107, in render
    self.content = self.rendered_content
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\response.py", line 82, in rendered_content
    template = self.resolve_template(self.template_name)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\response.py", line 64, in resolve_template
    return select_template(template, using=self.using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 53, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: admin/login.html
ERROR 2023-01-13 17:48:42,996 basehttp 124 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 85679
INFO 2023-01-13 17:49:00,584 basehttp 124 "GET /admin/ HTTP/1.1" 302 0
ERROR 2023-01-13 17:49:00,589 exception 135 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 215, in _get_response
    response = response.render()
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\response.py", line 107, in render
    self.content = self.rendered_content
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\response.py", line 82, in rendered_content
    template = self.resolve_template(self.template_name)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\response.py", line 64, in resolve_template
    return select_template(template, using=self.using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 53, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: admin/login.html
ERROR 2023-01-13 17:49:00,622 basehttp 124 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 85679
INFO 2023-01-13 17:53:27,782 basehttp 124 "GET /admin/ HTTP/1.1" 302 0
ERROR 2023-01-13 17:53:27,790 exception 135 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 215, in _get_response
    response = response.render()
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\response.py", line 107, in render
    self.content = self.rendered_content
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\response.py", line 82, in rendered_content
    template = self.resolve_template(self.template_name)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\response.py", line 64, in resolve_template
    return select_template(template, using=self.using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 53, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: admin/login.html
ERROR 2023-01-13 17:53:27,825 basehttp 124 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 85679
INFO 2023-01-13 17:57:40,411 basehttp 124 "GET /admin/ HTTP/1.1" 302 0
ERROR 2023-01-13 17:57:40,417 exception 135 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\core\handlers\base.py", line 215, in _get_response
    response = response.render()
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\response.py", line 107, in render
    self.content = self.rendered_content
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\response.py", line 82, in rendered_content
    template = self.resolve_template(self.template_name)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\response.py", line 64, in resolve_template
    return select_template(template, using=self.using)
  File "E:\project\MyEnvs\dj_py36\lib\site-packages\django\template\loader.py", line 53, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: admin/login.html
ERROR 2023-01-13 17:57:40,457 basehttp 124 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 85807
INFO 2023-01-13 17:57:41,747 basehttp 124 "GET /admin/ HTTP/1.1" 302 0
